### ISSUE TITLE
Encode

### ISSUE THREAD

**Issue by leslwingbast** [leslwingbast/CSD#1]
/// <summary>
        /// Encodes the supplied string message by formatting the input message first, then
        /// applying an initial CaesarShift then applying the keys within the List rotors. 
        /// All text should be uppercase, spaces replaced by the '?' character and all full
        /// stops '.' with a '€'. All other characters that are not [A..Z] or [a..z] should be 
        /// removed from the message.
        /// </summary>
        /// 
        /// Example input: "Deine Zauber binden wieder. Was die Mode streng geteilt.", 12, "HFPMRIBTJWYDXQLGUKOVSNAZEC"
        /// Expected output: "GKAPS?UOQNCQ?EBXMIG?CXWWDC€?IYM?GNO?FRSA?DQXHYR?IRSBDGE€"
        /// 
        /// <param name="message">The message to be encoded.</param>
        /// <param name="incrementNumber">The number of characters to shift when applying the
        /// Caesarshift.</param>
        /// <param name="rotors">A list of strings, each string is used for character substitution.</param>
        ///  
        /// <returns>An encoded string.</returns>
        /// 
        public static string Encode(string message, int incrementNumber, List<string> rotors)   
        {
            // TO DO - add your implementation
            throw new NotImplementedException();
        }

**Comment by mamy02** [comment]
Hi @leslwingbast @paulT1A ,
I hope everything's going well.
I think I finished coding the Encode Method last night - but I ran into some issues pushing it to origin (using the IDE)...
Maybe I messed up when I was cloning the Repos 😢.  
I'll probably try and clone it again tonight when I get home...

@leslwingbast when you a get a chance, would you mind configuring **Gitignore** to include Visual Studio please.

Thank you.

**Comment by paulT1A** [comment]
wow
cool that did the encode method!
i managed to get the clone done and can see the code -- a test push i did failed as well
hope you guys having a great day
P
________________________________

**Comment by leslwingbast** [comment]
Hi @mamy02
All good thanks, I am not too sure what you mean about the gitignore so I had a quick google on what you asked and it seems to be bringing back instructions for visual studio rather than in git but happy to change anything if you can guide me.

**Comment by mamy02** [comment]
Sorry guys I get very little time to respond to messages during the day...

@paulT1A  there are no many lines of codes in the Encode Method (fingers crossed - if it works as expected!)
@leslwingbast  I will probably try and double check my steps and see if that helps (as I created a new branch **featureBranch** I think - I will commit, then push to main locally first and see what happens...) - it was getting late and I was tired...  I will go back on one of those videos to see where you set GitIgnore in Github....

I have also released that I have 2 accounts: 1 linked to my gmail account and 1 linked to my ATU account - need a bit of tidying up....

I should be able to get back to you guys tonight

Thanks.

**Comment by mamy02** [comment]
Hi @leslwingbast 
Would you please add **https://github.com/MamadyKonate** to this repository please.
I gave you my personal one, and that is not properly set up.
Apologies!
Thanks.

**Comment by leslwingbast** [comment]
Hi @mamy02 
I have added the other account now. Do you want me to remove the other one to save confusion?

**Comment by mamy02** [comment]
Thanks @leslwingbast  - please let me ensure that one works for me.
I will let you know in a minute...

**Comment by MamadyKonate** [comment]
Thank you very much @leslwingbast 
I will do the cloning process from this one - fingers crossed!
I will let you guys know how I get on.

@paulT1A  did you get on OK?

**Comment by MamadyKonate** [comment]
@leslwingbast please remove the mamy02 - thanks again - appreciated.

**Comment by leslwingbast** [comment]
@MamadyKonate no problem, will remove the other one now.

**Comment by paulT1A** [comment]
I haven't coded my section yet - slammed in work -- will prob get on it tomorrow AM and give a the push a go
watch this space and bear with me 🙂
P

________________________________

**Comment by MamadyKonate** [comment]
I understand what you mean @paulT1A - but we will get there 🤞
I have just made a quick change to Encode Method and pushed it to origin - and it worked.
Thanks

**Comment by leslwingbast** [comment]
It will be tomorrow before I get a chance to look at it properly, have it started but need to figure out how to deal with keeping the converted character inside the uppercase alphabet now and not return symbols or small case letters. Have a solution in my head but head fried after work today so will leave it till tomorrow.

**Comment by paulT1A** [comment]
im deep fried too definitely
🙂we will get there!
P
________________________________

**Comment by MamadyKonate** [comment]
good idea - I find it sometimes, leaving it and coming back to it later does the job

**Comment by paulT1A** [comment]
Hey guys
Im around on teams 10am - 12 tomorrow if anyone wants to catch up -- little steps!
P
________________________________

**Comment by MamadyKonate** [comment]
I will be in work Paul - sorry.
I agree, a quick Team meeting will help

**Comment by paulT1A** [comment]
no worries
out at function tomorrow evening so may have to catch lecture recording
maybe after lecture if i get back in time we can grab 10 - 15 -- i should be back circa 7.30pm
see how we go
P
________________________________

**Comment by MamadyKonate** [comment]
All good - deployed into main
