### ISSUE TITLE
Decode

### ISSUE THREAD

**Issue by leslwingbast** [leslwingbast/CSD#2]
/// <summary>
        /// The Decode method should decode the supplied message by reversing the steps in the encode.
        /// The returned message should be in upper case with the character '?' replaced with spaces 
        /// and the '€' replaced with a full stop '.'. Remember to format the decoded message 
        /// correctly as specified in the FormatOutputMessage method.
        /// </summary>
        /// 
        /// Example input: "LQUKH?KTKUYXPQ?OV?UTH?GTR?OSTKBB€", 24, "YPSQFIUAGKZCXEMDBVRHNTJWLO"
        /// Expected output: "Aegir greatest of the sea giants."
        ///         
        /// <param name="message">The encoded message to be decoded</param>
        /// <param name="incrementNumber">The number of decrements to shift when applying 
        /// the Caesarshift.</param>
        /// <param name="rotors">A list of strings, each string is used for character substitution.</param>
        /// <returns>A decoded string.</returns>
        public static string Decode(string message, int incrementNumber, List<string> rotors)
        {
            // TO DO - add your implementation
            throw new NotImplementedException();
        }

**Comment by MamadyKonate** [comment]
@leslwingbast @paulT1A 
Final product deployed into main, and it looks really.
And everything seems to be working - Great job everyone.
This has been really a learning kerb for us all.
I think we are ready now for the next project.
Thank you both

**Comment by leslwingbast** [comment]
Well done guys, it was good to work together on this and get to know ye. Deffo learned a lot this week. Thanks

**Comment by paulT1A** [comment]
Thanks Guys
had to drive to Monaghan at 6am and Wifes birthday today so you haven't seen much of me - apologies-- I think the main brushes strokes of how Git works are there so well done all
to me the path is as follow

1 fork from main golden code -- this is what we did from shanes code
2 this is now our main -- each of us clone it to get a local copy
3 then in git we create a branch for our work -- to work on our issue
4once we have finished our work we push our code to this branch
5 the other member of the team also push to the branches they created for each issue
6 We take a look in Git hub to see differences in branches that have been pushed up
7 once happy we do a pull request to put all code into our fork -- the one we forked form shanes code (this would be our golden code as we can merge to shanes code)

this is a bit of brain dump but thought id throw it out there (totally think I'm missing something)

if you guys see big errors in this let me know -- really want a correct mental picture of Git for the upcoming project

have a great weekend guys
P
________________________________
