### ISSUE TITLE
ApplyRotor

### ISSUE THREAD

**Issue by MamadyKonate** [leslwingbast/CSD#5]
/// <summary>
        /// The ApplyRotor method should substitue each [A..Z] character in the input string
        /// with the corresponding character in the rotor. 
        ///                                         
        /// Example input message: "Apples", rotor: HFPMRIBTJWYDXQLGUKOVSNAZEC
        /// Example outout: "HGGDRO"
        /// </summary>
        /// Apply the rotor to the input message and return the scrambled message
        /// <param name="message"></param>
        /// <param name="rotor"></param>
        /// <returns>A string with each [A..Z] character in the input string replaced
        /// with the corresponding character in the rotor. </returns>
        private static string ApplyRotor(string message, string rotor)
        {

            // TO DO - add your implementation
            throw new NotImplementedException();
        }

**Comment by ampatzidhs** [comment]
Hello i am interstred to contribute to your project. I think i can solve some of the issues you have noted, are you interstred in pull request?

**Comment by MamadyKonate** [comment]
@leslwingbast @paulT1A 
There are a few commits I made but I could not assign a Reviewer to them.
Would mind reviewing them for me please and see what you think.
Commits after below (in featureBranch) should be grand -  Apologies!
**ApplyRotor Method implemented** 
Commits on Jan 11, 2023

You might have to show me how you assign a reviewer next time, as I just couldn't find it anywhere.
thank you.

**Comment by MamadyKonate** [comment]
So, you know, the following Methods were implemented in the last-ish commits

Encode(...)
ApplyRotor(...)
ReverseRotor(...)

Thanks.

**Comment by MamadyKonate** [comment]
All good - deployed into main
